name:                capability-graphs
version:             0.0.0.1
github:              "https://github.com/ben-jl/capability-graphs"
license:             BSD3
author:              "Ben LeValley"
maintainer:          "ben.levalley@gmail.com"
copyright:           "Ben LeValley 2021"

extra-source-files:
- README.md
- ChangeLog.md


description:         Please see the README on GitHub at <https://github.com/ben-jl/capability-graphs#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck >= 2.14.2 && < 2.15
- unordered-containers >= 0.2.10.0 && < 0.3
- hashable >= 1.3.0.0 && < 1.4
- text
- hspec >= 2.7.4 && < 2.8
- quickcheck-instances >= 0.3.25 && < 0.4

default-extensions:
  EmptyCase, LambdaCase, OverloadedStrings, BangPatterns, TupleSections
    , FlexibleContexts, FlexibleInstances, MultiParamTypeClasses, ConstraintKinds
    , KindSignatures, ScopedTypeVariables, RankNTypes 

library:
  source-dirs:
    - src
    - src/Data
  exposed-modules: Data.CapabilityGraph
  other-modules: Data.CapabilityGraph.Types
  ghc-options:
    - -Wall
    - -Wcompat

tests:
  capability-graphs-test:
    main:                Spec.hs
    other-modules: Test.GraphTests
    source-dirs:
    - test
    - test/Test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - capability-graphs
   
